server:
  port: 8011

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/account?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 950828
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: 'hikari'
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: 'SELECT 1'

security:
  my:
    private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIsFC8TxOaiqiNwi+PFUWMU5YOqllzThHyQg2j27Viw0BNDCBUA2vVxTR/tgGjjluSCaqjMzHraA7ZtQinvtD0jR7wwqmIUqtnlgkDAi62pTF3AANnuLRmRGdXX/Qy8x7T+1S6zm4215R+i3oMwM5FNJkr+z0If1nVtuEsoxyGnjAgMBAAECgYBfHle8K7Tg07YKsR8VuDl40FagliZMNxAgnx3UCR7f5cO5tlbzZcDQr+bbdxjZ/0xYo5p6p6qHAtYQY94tBrlifTYn5HbmQacaVQ2eHLYi4IhrzomH6CerSYL6KJPM8uccwOsPmTjYbrYO1Q5ewmmNau20WGYBb2PGwe9OARPMMQJBANF+hnpBceUi/dboFZCARleJlpMrz/T8Nf/jKTNuZqKapq5WZRTVgGPg6G2KumwV4TjD3iqzixddILpSYwi+VTkCQQCp4Xsp2lzIwcEtC2gAhxsbX+x3RThIcA7P33W3MXMtROjOMDNotVFXy8HavcGmskctK4gjBwsHtAOQ0UYKNLP7AkAqCPc2xLbzwSep3XumOPbkTak28o2RnKHBLHVx6m8RpXJYfOFfYs+WOuSoRjPNyD4ew75qVwhLsdYFTM6uTHKRAkEAlmdKawCoWxmn1SCfILB9YFwp+GLxdLi5dHNsPhfq2C6FS1/DdDXr4aZFaEvOcq6uc6Bx9EkdC+HlskaGEy0cFwJAA8LXayt346misCrkG3ZORUEFHoTCwTdFmqArzBBDiHmiUXddZaDmQsMyX3yVaYBCltl/n3tu7H5Gffht242oqA==
    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCLBQvE8TmoqojcIvjxVFjFOWDqpZc04R8kINo9u1YsNATQwgVANr1cU0f7YBo45bkgmqozMx62gO2bUIp77Q9I0e8MKpiFKrZ5YJAwIutqUxdwADZ7i0ZkRnV1/0MvMe0/tUus5uNteUfot6DMDORTSZK/s9CH9Z1bbhLKMchp4wIDAQAB

